### PR TITLE
Expose element instances from `Instances`

### PR DESCRIPTION
**Pull request by bplommer**

### CODE REVIEW

**Comment by milessabin** [comment]
This makes me a little nervous ... can you say a little bit about what you want this for?

**Comment by bplommer** [comment]
> This makes me a little nervous .

Why - from a type correctness point of view?

> can you say a little bit about what you want this for?

Not very specifically at the moment. The case I have in mind is deriving union codecs in Vulcan, where creating a codec requires a schema, and creating a union schema requires schemas for all the element types. But it's possible this could be done using some kind of fold that's less general and/or has weaker type guarantees than what I've done here - so I'm not certain whether this is needed.

**Comment by milessabin** [comment]
> Why - from a type correctness point of view?

From an "exposing" implementation details PoV.

> it's possible this could be done using some kind of fold that's less general and/or has weaker type guarantees than what I've done here - so I'm not certain whether this is needed.

I think for now I'd prefer it if you could see if you can come up with other higher level folds that do the job for you before we add this.

**Comment by bplommer** [comment]
> From an "exposing" implementation details PoV.

I'm curious why you see this as an implementation detail? The underlying `Array[Any]` is an implementation detail for sure, but this seems more like a canonical representation. 

> I think for now I'd prefer it if you could see if you can come up with other higher level folds that do the job for you before we add this.

Fair enough - I'll see what I can do!

**Pull request closed without merging**
