### PR TITLE
Use eager parameters when by-name is not necessary

### PR DESCRIPTION
**Pull request by joroKr21**
😄

### CODE REVIEW

**Comment by milessabin** [comment]
Hmm ... they really _should_ be necessary ... I need to dig in to why the seem not to be.

**Comment by joroKr21** [comment]
I think it's `Gen.derive` which takes functions with lazy parameters, no?

**Comment by TimWSpence** [comment]
> Hmm ... they really _should_ be necessary ... I need to dig in to why the seem not to be.

This is something that I've been meaning to look into for a while - I've never seen anything fail (even for recursive data structures) due to strict given instances

**Comment by joroKr21** [comment]
@milessabin what should we do with this PR?

**Comment by joroKr21** [comment]
I'm gonna merge this - it's only tests anyway 😄

**Comment by milessabin** [comment]
Sorry I should have replied earlier ... :+1:

**Pull request merged**
